var stats = [
      {
        "game": "1",
        "opponent": "SAC",
        "outcome": "W (+18)",
        "fieldgoalper": ".412",
        "threepointers": "2",
        "freethrowper": ".889",
        "rebounds": "10",
        "assists": "5",
        "steals": "6",
        "blocks": "0",
        "turnovers": "4",
        "fouls": "5",
        "points": "24",
        "gamescore": "21.4",
        "plusminus": "+20"
      },
      {
        "game": "2",
        "opponent": "LAL",
        "outcome": "W (+23)",
        "fieldgoalper": ".526",
        "threepointers": "3",
        "freethrowper": "1.000",
        "rebounds": "5",
        "assists": "10",
        "steals": "3",
        "blocks": "0",
        "turnovers": "2",
        "fouls": "3",
        "points": "31",
        "gamescore": "30.0",
        "plusminus": "+30"
      },
      {
        "game": "3",
        "opponent": "POR",
        "outcome": "W (+5)",
        "fieldgoalper": ".333",
        "threepointers": "1",
        "freethrowper": "1.000",
        "rebounds": "5",
        "assists": "6",
        "steals": "2",
        "blocks": "0",
        "turnovers": "3",
        "fouls": "1",
        "points": "21",
        "gamescore": "15.5",
        "plusminus": "+12"
      },
      {
        "game": "4",
        "opponent": "LAC",
        "outcome": "W (+17)",
        "fieldgoalper": ".500",
        "threepointers": "4",
        "freethrowper": "1.000",
        "rebounds": "6",
        "assists": "7",
        "steals": "1",
        "blocks": "0",
        "turnovers": "5",
        "fouls": "4",
        "points": "28",
        "gamescore": "20.1",
        "plusminus": "+21"
      },
      {
        "game": "5",
        "opponent": "HOU",
        "outcome": "W (+11)",
        "fieldgoalper": ".684",
        "threepointers": "6",
        "freethrowper": "1.000",
        "rebounds": "9",
        "assists": "5",
        "steals": "4",
        "blocks": "0",
        "turnovers": "5",
        "fouls": "2",
        "points": "34",
        "gamescore": "30.7",
        "plusminus": "+13"
      },
      {
        "game": "6",
        "opponent": "PHO",
        "outcome": "L (-12)",
        "fieldgoalper": ".500",
        "threepointers": "4",
        "freethrowper": "1.000",
        "rebounds": "2",
        "assists": "10",
        "steals": "5",
        "blocks": "0",
        "turnovers": "10",
        "fouls": "5",
        "points": "28",
        "gamescore": "18.6",
        "plusminus": "-6"
      },
      {
        "game": "7",
        "opponent": "SAS",
        "outcome": "L (-13)",
        "fieldgoalper": ".389",
        "threepointers": "0",
        "freethrowper": "1.000",
        "rebounds": "6",
        "assists": "5",
        "steals": "0",
        "blocks": "0",
        "turnovers": "3",
        "fouls": "2",
        "points": "16",
        "gamescore": "7.7",
        "plusminus": "-18"
      },
      {
        "game": "8",
        "opponent": "BRK",
        "outcome": "W (+8)",
        "fieldgoalper": ".500",
        "threepointers": "3",
        "freethrowper": "1.000",
        "rebounds": "3",
        "assists": "5",
        "steals": "0",
        "blocks": "0",
        "turnovers": "3",
        "fouls": "5",
        "points": "17",
        "gamescore": "10.8",
        "plusminus": "+6"
      },
      {
        "game": "9",
        "opponent": "CHO",
        "outcome": "W (+25)",
        "fieldgoalper": ".533",
        "threepointers": "3",
        "freethrowper": ".000",
        "rebounds": "5",
        "assists": "9",
        "steals": "1",
        "blocks": "0",
        "turnovers": "1",
        "fouls": "3",
        "points": "19",
        "gamescore": "18.7",
        "plusminus": "+23"
      },
      {
        "game": "10",
        "opponent": "LAL",
        "outcome": "W (+21)",
        "fieldgoalper": ".526",
        "threepointers": "5",
        "freethrowper": "1.000",
        "rebounds": "4",
        "assists": "15",
        "steals": "1",
        "blocks": "0",
        "turnovers": "3",
        "fouls": "0",
        "points": "30",
        "gamescore": "30.4",
        "plusminus": "+27"
      },
      {
        "game": "11",
        "opponent": "UTA",
        "outcome": "W (+13)",
        "fieldgoalper": ".333",
        "threepointers": "2",
        "freethrowper": "",
        "rebounds": "5",
        "assists": "10",
        "steals": "2",
        "blocks": "0",
        "turnovers": "4",
        "fouls": "2",
        "points": "8",
        "gamescore": "8.6",
        "plusminus": "+23"
      },
      {
        "game": "12",
        "opponent": "OKC",
        "outcome": "W (+5)",
        "fieldgoalper": ".333",
        "threepointers": "2",
        "freethrowper": ".750",
        "rebounds": "6",
        "assists": "6",
        "steals": "1",
        "blocks": "0",
        "turnovers": "1",
        "fouls": "0",
        "points": "15",
        "gamescore": "12.1",
        "plusminus": "+2"
      },
      {
        "game": "13",
        "opponent": "MIA",
        "outcome": "W (+17)",
        "fieldgoalper": ".632",
        "threepointers": "8",
        "freethrowper": ".889",
        "rebounds": "6",
        "assists": "7",
        "steals": "3",
        "blocks": "1",
        "turnovers": "2",
        "fouls": "2",
        "points": "40",
        "gamescore": "38.7",
        "plusminus": "+28"
      },
      {
        "game": "14",
        "opponent": "ORL",
        "outcome": "W (+15)",
        "fieldgoalper": ".692",
        "threepointers": "6",
        "freethrowper": ".800",
        "rebounds": "5",
        "assists": "8",
        "steals": "0",
        "blocks": "0",
        "turnovers": "1",
        "fouls": "1",
        "points": "28",
        "gamescore": "28.2",
        "plusminus": "+22"
      },
      {
        "game": "15",
        "opponent": "CHO",
        "outcome": "W (+5)",
        "fieldgoalper": ".450",
        "threepointers": "1",
        "freethrowper": "1.000",
        "rebounds": "4",
        "assists": "6",
        "steals": "1",
        "blocks": "2",
        "turnovers": "4",
        "fouls": "4",
        "points": "26",
        "gamescore": "18.2",
        "plusminus": "+16"
      },
      {
        "game": "16",
        "opponent": "DET",
        "outcome": "W (+11)",
        "fieldgoalper": ".556",
        "threepointers": "1",
        "freethrowper": ".833",
        "rebounds": "3",
        "assists": "10",
        "steals": "1",
        "blocks": "0",
        "turnovers": "1",
        "fouls": "2",
        "points": "16",
        "gamescore": "18.8",
        "plusminus": "+11"
      },
      {
        "game": "17",
        "opponent": "ORL",
        "outcome": "W (+1)",
        "fieldgoalper": ".471",
        "threepointers": "3",
        "freethrowper": "1.000",
        "rebounds": "4",
        "assists": "5",
        "steals": "0",
        "blocks": "0",
        "turnovers": "4",
        "fouls": "2",
        "points": "22",
        "gamescore": "13.6",
        "plusminus": "+8"
      },
      {
        "game": "18",
        "opponent": "NOP",
        "outcome": "W (+27)",
        "fieldgoalper": ".471",
        "threepointers": "3",
        "freethrowper": "",
        "rebounds": "3",
        "assists": "11",
        "steals": "4",
        "blocks": "1",
        "turnovers": "2",
        "fouls": "0",
        "points": "19",
        "gamescore": "21.6",
        "plusminus": "+11"
      },
      {
        "game": "19",
        "opponent": "CHI",
        "outcome": "W (+10)",
        "fieldgoalper": ".357",
        "threepointers": "1",
        "freethrowper": ".889",
        "rebounds": "6",
        "assists": "7",
        "steals": "1",
        "blocks": "0",
        "turnovers": "3",
        "fouls": "2",
        "points": "19",
        "gamescore": "15.1",
        "plusminus": "+7"
      },
      {
        "game": "20",
        "opponent": "MIN",
        "outcome": "W (+16)",
        "fieldgoalper": ".500",
        "threepointers": "1",
        "freethrowper": "",
        "rebounds": "4",
        "assists": "7",
        "steals": "3",
        "blocks": "1",
        "turnovers": "3",
        "fouls": "3",
        "points": "21",
        "gamescore": "17.0",
        "plusminus": "+22"
      },
      {
        "game": "21",
        "opponent": "HOU",
        "outcome": "W (+12)",
        "fieldgoalper": ".533",
        "threepointers": "3",
        "freethrowper": "1.000",
        "rebounds": "7",
        "assists": "7",
        "steals": "0",
        "blocks": "0",
        "turnovers": "4",
        "fouls": "3",
        "points": "20",
        "gamescore": "14.9",
        "plusminus": "+16"
      },
      {
        "game": "22",
        "opponent": "DAL",
        "outcome": "W (+7)",
        "fieldgoalper": ".409",
        "threepointers": "3",
        "freethrowper": ".889",
        "rebounds": "3",
        "assists": "8",
        "steals": "2",
        "blocks": "0",
        "turnovers": "1",
        "fouls": "1",
        "points": "29",
        "gamescore": "23.9",
        "plusminus": "+13"
      },
      {
        "game": "23",
        "opponent": "NOP",
        "outcome": "W (+6)",
        "fieldgoalper": ".524",
        "threepointers": "6",
        "freethrowper": "1.000",
        "rebounds": "7",
        "assists": "7",
        "steals": "1",
        "blocks": "0",
        "turnovers": "6",
        "fouls": "1",
        "points": "34",
        "gamescore": "25.3",
        "plusminus": "+5"
      },
      {
        "game": "24",
        "opponent": "MEM",
        "outcome": "L (-7)",
        "fieldgoalper": ".360",
        "threepointers": "1",
        "freethrowper": "",
        "rebounds": "7",
        "assists": "6",
        "steals": "4",
        "blocks": "0",
        "turnovers": "3",
        "fouls": "2",
        "points": "19",
        "gamescore": "11.6",
        "plusminus": "+16"
      },
      {
        "game": "25",
        "opponent": "OKC",
        "outcome": "W (+5)",
        "fieldgoalper": ".583",
        "threepointers": "5",
        "freethrowper": "1.000",
        "rebounds": "7",
        "assists": "9",
        "steals": "4",
        "blocks": "1",
        "turnovers": "4",
        "fouls": "0",
        "points": "34",
        "gamescore": "33.5",
        "plusminus": "+6"
      },
      {
        "game": "26",
        "opponent": "SAC",
        "outcome": "W (+20)",
        "fieldgoalper": ".417",
        "threepointers": "1",
        "freethrowper": "1.000",
        "rebounds": "2",
        "assists": "11",
        "steals": "3",
        "blocks": "0",
        "turnovers": "1",
        "fouls": "1",
        "points": "12",
        "gamescore": "15.5",
        "plusminus": "+15"
      }
    ];